export const products = [
  {
    id: "1",
    name: "Apple iPhone 15 (128GB) - Black Titanium",
    category: "Electronics",
    subcategory: "Smartphones",
    brand: "Apple",
    price: 69999,
    mrp: 79900,
    discount: 12,
    rating: 4.6,
    reviews: 25847,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
      "https://images.unsplash.com/photo-1634403665481-74948d815f03?w=400&q=80",
      "https://images.unsplash.com/photo-1512054502232-10a0a035d672?w=400&q=80"
    ],
    badge: "Bestseller",
    highlights: ["6.1-inch Super Retina XDR display", "A16 Bionic chip", "48MP Main Camera", "USB-C connector", "Up to 26 hours video playback"],
    description: "iPhone 15 features a durable color-infused glass and aluminum design. Advanced camera system with 48MP main and 12MP ultra wide. A16 Bionic — the ultimate smartphone chip.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "Tomorrow",
    colors: ["Black Titanium", "White Titanium", "Blue", "Pink", "Yellow"],
    sizes: [],
    seller: "Apple India Authorized Seller",
    isFeatured: true
  },
  {
    id: "2",
    name: "Samsung Galaxy S24 Ultra 5G (256GB) - Titanium Gray",
    category: "Electronics",
    subcategory: "Smartphones",
    brand: "Samsung",
    price: 99999,
    mrp: 134999,
    discount: 26,
    rating: 4.5,
    reviews: 18432,
    image: "https://images.unsplash.com/photo-1634403665481-74948d815f03?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1634403665481-74948d815f03?w=400&q=80",
      "https://images.pexels.com/photos/215581/pexels-photo-215581.jpeg?w=400",
      "https://images.unsplash.com/photo-1512054502232-10a0a035d672?w=400&q=80"
    ],
    badge: "Top Rated",
    highlights: ["6.8-inch QHD+ Dynamic AMOLED", "Snapdragon 8 Gen 3", "200MP quad camera", "S Pen included", "5000mAh battery"],
    description: "Samsung Galaxy S24 Ultra with built-in S Pen redefines productivity and creativity. Equipped with ProVisual Engine and 200MP camera for breathtaking shots.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "Tomorrow",
    colors: ["Titanium Gray", "Titanium Black", "Titanium Violet", "Titanium Yellow"],
    sizes: [],
    seller: "Samsung India Pvt Ltd",
    isFeatured: true
  },
  {
    id: "3",
    name: "OnePlus 12 5G (256GB) - Flowy Emerald",
    category: "Electronics",
    subcategory: "Smartphones",
    brand: "OnePlus",
    price: 54999,
    mrp: 64999,
    discount: 15,
    rating: 4.4,
    reviews: 9821,
    image: "https://images.pexels.com/photos/215581/pexels-photo-215581.jpeg?w=400",
    images: [
      "https://images.pexels.com/photos/215581/pexels-photo-215581.jpeg?w=400",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80"
    ],
    badge: "Trending",
    highlights: ["6.82-inch 2K AMOLED ProXDR Display", "Snapdragon 8 Gen 3", "Hasselblad Camera", "100W SUPERVOOC Charging", "5400mAh battery"],
    description: "OnePlus 12 with Hasselblad Camera System. Experience the future of flagship performance with Snapdragon 8 Gen 3 and unmatched charging speed.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["Flowy Emerald", "Silky Black"],
    sizes: [],
    seller: "OnePlus India",
    isFeatured: false
  },
  {
    id: "4",
    name: "Redmi Note 13 Pro+ 5G (256GB) - Mystic Silver",
    category: "Electronics",
    subcategory: "Smartphones",
    brand: "Redmi",
    price: 29999,
    mrp: 37999,
    discount: 21,
    rating: 4.3,
    reviews: 14567,
    image: "https://images.unsplash.com/photo-1512054502232-10a0a035d672?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1512054502232-10a0a035d672?w=400&q=80",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80"
    ],
    badge: "Value for Money",
    highlights: ["6.67-inch 1.5K AMOLED CurvedDisplay", "MediaTek Dimensity 7200 Ultra", "200MP OIS Camera", "120W HyperCharge", "IP68 water resistant"],
    description: "Redmi Note 13 Pro+ brings premium features at an accessible price. 200MP camera, curved AMOLED display, and 120W fast charging make it a true flagship killer.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "Tomorrow",
    colors: ["Mystic Silver", "Midnight Black", "Fusion Purple"],
    sizes: [],
    seller: "Xiaomi India",
    isFeatured: false
  },
  {
    id: "5",
    name: "Apple MacBook Air 15-inch (M3, 8GB, 256GB)",
    category: "Electronics",
    subcategory: "Laptops",
    brand: "Apple",
    price: 109990,
    mrp: 124900,
    discount: 12,
    rating: 4.7,
    reviews: 5621,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&q=80",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&q=80"
    ],
    badge: "Bestseller",
    highlights: ["15.3-inch Liquid Retina display", "Apple M3 chip", "Up to 18 hours battery", "MagSafe charging", "Fanless silent design"],
    description: "MacBook Air with M3 chip. Supercharged by Apple silicon, with a beautiful 15-inch Liquid Retina display, all-day battery life, and a fanless design.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["Midnight", "Starlight", "Space Gray", "Sky Blue"],
    sizes: [],
    seller: "Apple India Authorized Seller",
    isFeatured: true
  },
  {
    id: "6",
    name: "Dell Inspiron 15 3000 (Core i5, 16GB, 512GB SSD)",
    category: "Electronics",
    subcategory: "Laptops",
    brand: "Dell",
    price: 49990,
    mrp: 67990,
    discount: 26,
    rating: 4.2,
    reviews: 8432,
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80"
    ],
    badge: "Great Deal",
    highlights: ["15.6-inch FHD Anti-Glare Display", "Intel Core i5-1235U", "16GB DDR4 RAM", "512GB SSD", "Windows 11 Home"],
    description: "Dell Inspiron 15 3000 is perfect for everyday computing. Packed with Intel Core i5 processor, 16GB RAM, and 512GB SSD for fast performance.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "3 Days",
    colors: ["Carbon Black"],
    sizes: [],
    seller: "Dell Technologies India",
    isFeatured: false
  },
  {
    id: "7",
    name: "Lenovo IdeaPad Slim 3 (Ryzen 5, 8GB, 512GB SSD)",
    category: "Electronics",
    subcategory: "Laptops",
    brand: "Lenovo",
    price: 38999,
    mrp: 52990,
    discount: 26,
    rating: 4.1,
    reviews: 7234,
    image: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&q=80",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&q=80"
    ],
    badge: "Value Pick",
    highlights: ["15.6-inch FHD IPS Display", "AMD Ryzen 5 7520U", "8GB LPDDR5 RAM", "512GB SSD", "Up to 7 hours battery"],
    description: "Lenovo IdeaPad Slim 3 with AMD Ryzen 5. Get fast performance and great display quality with long battery backup for students and professionals.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["Arctic Grey", "Abyss Blue"],
    sizes: [],
    seller: "Lenovo India Pvt Ltd",
    isFeatured: false
  },
  {
    id: "8",
    name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    category: "Electronics",
    subcategory: "Headphones",
    brand: "Sony",
    price: 24990,
    mrp: 34990,
    discount: 29,
    rating: 4.7,
    reviews: 12456,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&q=80"
    ],
    badge: "Top Rated",
    highlights: ["Industry-leading noise cancellation", "30 hours battery with ANC on", "Quick Charge - 3min = 3 hours", "Multipoint connection", "Speak-to-chat technology"],
    description: "Sony WH-1000XM5 headphones with best-in-class noise cancellation. Features 8 microphones, dual noise sensor technology, and HD sound for an unparalleled listening experience.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "Tomorrow",
    colors: ["Black", "Silver"],
    sizes: [],
    seller: "Sony India Pvt Ltd",
    isFeatured: true
  },
  {
    id: "9",
    name: "boAt Rockerz 550 Bluetooth Headphones",
    category: "Electronics",
    subcategory: "Headphones",
    brand: "boAt",
    price: 1499,
    mrp: 4990,
    discount: 70,
    rating: 4.1,
    reviews: 43892,
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80"
    ],
    badge: "70% Off",
    highlights: ["20 hours playback", "40mm driver", "Padded earcups", "Foldable design", "1.5m detachable cable"],
    description: "boAt Rockerz 550 delivers immersive audio experience with 40mm drivers and 20 hours of playback. Ergonomic cushioned earcups provide all-day comfort.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["Luscious Black", "Bold Red", "Stone Blue"],
    sizes: [],
    seller: "Imagine Marketing",
    isFeatured: false
  },
  {
    id: "10",
    name: "Samsung 55-inch Crystal 4K Smart TV (UA55CUE60)",
    category: "Electronics",
    subcategory: "Televisions",
    brand: "Samsung",
    price: 44990,
    mrp: 80900,
    discount: 44,
    rating: 4.3,
    reviews: 6784,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400&q=80",
      "https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=400&q=80"
    ],
    badge: "44% Off",
    highlights: ["55-inch Crystal 4K Display", "Crystal Processor 4K", "Airslim design", "Alexa and Google Assistant", "3 HDMI, 2 USB ports"],
    description: "Samsung 55-inch Crystal 4K Smart TV with Tizen OS. Enjoy crisp 4K resolution, smart features with Alexa/Google Assistant, and sleek AirSlim design.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "3 Days",
    colors: ["Black"],
    sizes: [],
    seller: "Samsung India Pvt Ltd",
    isFeatured: true
  },
  {
    id: "11",
    name: "Allen Solly Men's Slim Fit Formal Shirt",
    category: "Fashion",
    subcategory: "Men's Shirts",
    brand: "Allen Solly",
    price: 799,
    mrp: 1999,
    discount: 60,
    rating: 4.2,
    reviews: 8921,
    image: "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=400&q=80",
      "https://images.unsplash.com/photo-1611040025375-b76ed9e3ece9?w=400&q=80"
    ],
    badge: "60% Off",
    highlights: ["100% Cotton fabric", "Slim fit", "Full sleeves", "Machine washable", "Formal occasion"],
    description: "Allen Solly Men's Slim Fit shirt crafted from premium 100% cotton fabric. Perfect for formal occasions with clean lines and comfortable fit.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["White", "Light Blue", "Navy", "Grey"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    seller: "Allen Solly Fashion",
    isFeatured: false
  },
  {
    id: "12",
    name: "Roadster Men's Slim Fit Jeans",
    category: "Fashion",
    subcategory: "Men's Jeans",
    brand: "Roadster",
    price: 999,
    mrp: 2499,
    discount: 60,
    rating: 4.0,
    reviews: 15234,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&q=80",
      "https://images.unsplash.com/photo-1501012923-e478ed8e2f35?w=400&q=80"
    ],
    badge: "Trending",
    highlights: ["98% Cotton, 2% Elastane", "Slim fit", "5 pocket styling", "Mid rise", "Light wash"],
    description: "Roadster Men's Slim Fit Jeans with stretchable fabric for all-day comfort. Classic 5-pocket design with modern slim silhouette.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["Dark Blue", "Light Blue", "Black"],
    sizes: ["28", "30", "32", "34", "36"],
    seller: "Myntra Jabong India Pvt Ltd",
    isFeatured: false
  },
  {
    id: "13",
    name: "Libas Women's Floral Kurta with Dupatta",
    category: "Fashion",
    subcategory: "Women's Kurtas",
    brand: "Libas",
    price: 899,
    mrp: 2099,
    discount: 57,
    rating: 4.3,
    reviews: 11234,
    image: "https://images.unsplash.com/photo-1583316174775-bd6dc0e9f298?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1583316174775-bd6dc0e9f298?w=400&q=80",
      "https://images.unsplash.com/photo-1588117260148-b47818741c74?w=400&q=80"
    ],
    badge: "57% Off",
    highlights: ["Rayon fabric", "Floral print", "A-line kurta", "Dupatta included", "Hand wash recommended"],
    description: "Libas Women's floral printed kurta set in soft rayon fabric. Comfortable A-line silhouette paired with a matching dupatta for a complete ethnic look.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "3 Days",
    colors: ["Pink", "Blue", "Yellow", "Green"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    seller: "Libas Designs",
    isFeatured: false
  },
  {
    id: "14",
    name: "W Women's Printed A-Line Dress",
    category: "Fashion",
    subcategory: "Women's Dresses",
    brand: "W",
    price: 1299,
    mrp: 2799,
    discount: 54,
    rating: 4.2,
    reviews: 7823,
    image: "https://images.unsplash.com/photo-1683223059099-e2f012c65630?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1683223059099-e2f012c65630?w=400&q=80",
      "https://images.unsplash.com/photo-1583316174775-bd6dc0e9f298?w=400&q=80"
    ],
    badge: "Popular",
    highlights: ["Polyester blend", "A-line silhouette", "Printed design", "Short sleeves", "Regular fit"],
    description: "W Women's printed A-line dress for modern Indian woman. Contemporary design with comfortable polyester blend fabric.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["Multicolor", "Blue", "Orange"],
    sizes: ["XS", "S", "M", "L", "XL"],
    seller: "TCNS Clothing Co Ltd",
    isFeatured: false
  },
  {
    id: "15",
    name: "Prestige IRIS 750W Mixer Grinder (3 Jars)",
    category: "Home & Kitchen",
    subcategory: "Mixer Grinders",
    brand: "Prestige",
    price: 2499,
    mrp: 4500,
    discount: 44,
    rating: 4.3,
    reviews: 18921,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80",
      "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80"
    ],
    badge: "44% Off",
    highlights: ["750 Watt motor", "3 Stainless Steel Jars", "3 Speed control + Pulse", "Ergonomic handles", "2 Year Warranty"],
    description: "Prestige IRIS 750W Mixer Grinder with 3 stainless steel jars for all your grinding and mixing needs. Powerful motor with 3 speed settings.",
    inStock: true,
    deliveryCharge: 40,
    deliveryDate: "3 Days",
    colors: ["White & Grey"],
    sizes: [],
    seller: "TTK Prestige Ltd",
    isFeatured: false
  },
  {
    id: "16",
    name: "Milton Thermosteel Flip Lid Flask 1000ml",
    category: "Home & Kitchen",
    subcategory: "Bottles & Flasks",
    brand: "Milton",
    price: 549,
    mrp: 1295,
    discount: 58,
    rating: 4.4,
    reviews: 31245,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80",
      "https://images.unsplash.com/photo-1594897891784-abf9f6a77dcb?w=400&q=80"
    ],
    badge: "Hot Seller",
    highlights: ["Keeps beverages hot/cold 24 hours", "304 food grade stainless steel", "Leak-proof flip lid", "1000ml capacity", "5 Year Warranty"],
    description: "Milton Thermosteel Flip Lid Flask keeps beverages hot or cold for 24 hours. Made with premium 304 food grade stainless steel, rust and stain resistant.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["Silver", "Black", "Blue", "Red"],
    sizes: ["500ml", "750ml", "1000ml"],
    seller: "Sunhill Trading Company",
    isFeatured: false
  },
  {
    id: "17",
    name: "Lakme Absolute Perfect Radiance Skin Lightening Serum",
    category: "Beauty",
    subcategory: "Serums",
    brand: "Lakme",
    price: 499,
    mrp: 799,
    discount: 38,
    rating: 4.1,
    reviews: 12543,
    image: "https://images.pexels.com/photos/31812004/pexels-photo-31812004.jpeg?w=400",
    images: [
      "https://images.pexels.com/photos/31812004/pexels-photo-31812004.jpeg?w=400",
      "https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?w=400"
    ],
    badge: "38% Off",
    highlights: ["3x Skin Lightening Complex", "Micro crystals for glowing skin", "Suitable for all skin types", "Dermatologist tested", "30ml serum"],
    description: "Lakme Absolute Perfect Radiance Serum with 3x Skin Lightening Complex. Micro crystals work deep within the skin layers to give you a visibly brighter complexion.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "Tomorrow",
    colors: [],
    sizes: [],
    seller: "Hindustan Unilever Ltd",
    isFeatured: false
  },
  {
    id: "18",
    name: "Mamaearth Vitamin C Face Wash (100ml)",
    category: "Beauty",
    subcategory: "Face Wash",
    brand: "Mamaearth",
    price: 249,
    mrp: 349,
    discount: 29,
    rating: 4.3,
    reviews: 45821,
    image: "https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?w=400",
    images: [
      "https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?w=400",
      "https://images.pexels.com/photos/31812004/pexels-photo-31812004.jpeg?w=400"
    ],
    badge: "Popular",
    highlights: ["Made with Vitamin C & Turmeric", "Removes tan & brightens skin", "Free from harsh chemicals", "Dermatologically tested", "Made Safe Certified"],
    description: "Mamaearth Vitamin C Face Wash with Vitamin C and Turmeric that gently cleanses, removes tan, and brightens skin. Natural and toxin-free formula.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "Tomorrow",
    colors: [],
    sizes: ["100ml", "200ml"],
    seller: "Honasa Consumer Pvt Ltd",
    isFeatured: false
  },
  {
    id: "19",
    name: "Puma Men's Running Shoes - Softride Rift",
    category: "Sports",
    subcategory: "Sports Shoes",
    brand: "Puma",
    price: 2499,
    mrp: 4599,
    discount: 46,
    rating: 4.3,
    reviews: 8721,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&q=80"
    ],
    badge: "46% Off",
    highlights: ["Softride foam cushioning", "Rubber outsole for grip", "Breathable mesh upper", "Lace-up closure", "Running shoes"],
    description: "Puma Softride Rift Running Shoes with lightweight Softride foam cushioning for superior comfort. Breathable mesh upper keeps your feet cool during workouts.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["White", "Black", "Navy"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    seller: "Puma Sports India Pvt Ltd",
    isFeatured: false
  },
  {
    id: "20",
    name: "Whirlpool 1.5 Ton 5 Star Inverter Split AC (2023)",
    category: "Appliances",
    subcategory: "Air Conditioners",
    brand: "Whirlpool",
    price: 32999,
    mrp: 42900,
    discount: 23,
    rating: 4.1,
    reviews: 4321,
    image: "https://images.unsplash.com/photo-1631545806609-e6b9f8b7f3e0?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1631545806609-e6b9f8b7f3e0?w=400&q=80"
    ],
    badge: "Energy Saver",
    highlights: ["1.5 Ton capacity", "5 Star BEE Rating", "Inverter compressor", "6th Sense Technology", "2 Year Comprehensive Warranty"],
    description: "Whirlpool 1.5 Ton 5 Star Inverter Split AC with 6th Sense Technology for intelligent cooling. 5 Star energy rating saves up to 50% electricity.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "5 Days",
    colors: ["White"],
    sizes: [],
    seller: "Whirlpool of India Ltd",
    isFeatured: false
  },
  {
    id: "21",
    name: "LG 6.5 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine",
    category: "Appliances",
    subcategory: "Washing Machines",
    brand: "LG",
    price: 24990,
    mrp: 38900,
    discount: 36,
    rating: 4.4,
    reviews: 5678,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80"
    ],
    badge: "36% Off",
    highlights: ["6.5 kg capacity", "5 Star energy rating", "AI DD Technology", "Steam Technology", "10 Year Motor Warranty"],
    description: "LG 6.5 kg Inverter Front Loading Washing Machine with AI DD Technology. Steam Technology removes 99.9% allergens. 10 year motor warranty included.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "5 Days",
    colors: ["White"],
    sizes: [],
    seller: "LG Electronics India Pvt Ltd",
    isFeatured: false
  },
  {
    id: "22",
    name: "adidas Men's Adilette Aqua Slide Flip Flops",
    category: "Fashion",
    subcategory: "Footwear",
    brand: "Adidas",
    price: 999,
    mrp: 1999,
    discount: 50,
    rating: 4.4,
    reviews: 22341,
    image: "https://images.unsplash.com/photo-1511452885600-a3d2c9147a68?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1511452885600-a3d2c9147a68?w=400&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80"
    ],
    badge: "50% Off",
    highlights: ["Cloudfoam footbed", "Synthetic upper", "Quick dry material", "Lightweight design", "Perfect for pool/beach"],
    description: "adidas Adilette Aqua Slides with comfortable Cloudfoam footbed. Quick-dry material makes these perfect for pool, beach, or casual use.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["Black", "White", "Blue", "Red"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    seller: "Adidas India Marketing Pvt Ltd",
    isFeatured: false
  },
  {
    id: "23",
    name: "Philips HL7756 750W Mixer Grinder with 3 Jars",
    category: "Home & Kitchen",
    subcategory: "Mixer Grinders",
    brand: "Philips",
    price: 3299,
    mrp: 5295,
    discount: 38,
    rating: 4.2,
    reviews: 9876,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80"
    ],
    badge: "Trending",
    highlights: ["750W PowerPro motor", "3 stainless steel jars", "4 speed settings", "Flow breakers in jars", "2 Year Warranty"],
    description: "Philips HL7756 Mixer Grinder with 750W PowerPro motor and 3 multipurpose jars. Flow breakers ensure efficient grinding of all ingredients.",
    inStock: true,
    deliveryCharge: 40,
    deliveryDate: "3 Days",
    colors: ["Blue & White"],
    sizes: [],
    seller: "Philips India Ltd",
    isFeatured: false
  },
  {
    id: "24",
    name: "Nike Air Max 270 React Running Shoes",
    category: "Sports",
    subcategory: "Sports Shoes",
    brand: "Nike",
    price: 7995,
    mrp: 11995,
    discount: 33,
    rating: 4.5,
    reviews: 7654,
    image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80"
    ],
    badge: "33% Off",
    highlights: ["Air Max unit for comfort", "React foam midsole", "Rubber waffle outsole", "Stretch woven upper", "Everyday running shoe"],
    description: "Nike Air Max 270 React combines Nike's two iconic technologies. The large Air unit and React foam work together for responsive, lightweight cushioning.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "2 Days",
    colors: ["White/Black", "Red/White", "Black"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    seller: "Nike Sports India Pvt Ltd",
    isFeatured: true
  },
  {
    id: "25",
    name: "Sugar Cosmetics Transfer-Proof Lipstick - Matte",
    category: "Beauty",
    subcategory: "Lipstick",
    brand: "Sugar Cosmetics",
    price: 449,
    mrp: 599,
    discount: 25,
    rating: 4.4,
    reviews: 18234,
    image: "https://images.unsplash.com/photo-1586495777744-4e6232bf2e54?w=400&q=80",
    images: [
      "https://images.unsplash.com/photo-1586495777744-4e6232bf2e54?w=400&q=80",
      "https://images.pexels.com/photos/31812004/pexels-photo-31812004.jpeg?w=400"
    ],
    badge: "Popular",
    highlights: ["Transfer-proof formula", "Non-drying matte finish", "8 hour wear", "Enriched with Vitamin E", "20+ shades available"],
    description: "Sugar Cosmetics Transfer-Proof Matte Lipstick with 8-hour wear formula. Enriched with Vitamin E for non-drying comfortable matte finish.",
    inStock: true,
    deliveryCharge: 0,
    deliveryDate: "Tomorrow",
    colors: ["Crimson Red", "Nude Brown", "Pink", "Berry", "Coral"],
    sizes: [],
    seller: "A boutique item (SUGAR Cosmetics)",
    isFeatured: false
  }
];

export const categories = [
  {
    name: "Electronics",
    subcategories: ["Mobiles", "Laptops", "Tablets", "Smart TVs", "Cameras", "Headphones", "Speakers", "Wearables"]
  },
  {
    name: "Fashion",
    subcategories: ["Men's Clothing", "Women's Clothing", "Kids' Fashion", "Footwear", "Watches", "Jewellery", "Handbags", "Sunglasses"]
  },
  {
    name: "Home",
    subcategories: ["Furniture", "Bed & Bath", "Home Decor", "Kitchen & Dining", "Lighting", "Curtains", "Cleaning Supplies", "Storage"]
  },
  {
    name: "Appliances",
    subcategories: ["Air Conditioners", "Refrigerators", "Washing Machines", "Microwaves", "Dishwashers", "Water Purifiers", "Chimneys", "Fans"]
  },
  {
    name: "Beauty",
    subcategories: ["Skincare", "Haircare", "Makeup", "Fragrances", "Body Care", "Men's Grooming", "Nail Care", "Eye Care"]
  },
  {
    name: "Toys",
    subcategories: ["Action Figures", "Board Games", "Remote Control", "Dolls", "Educational", "Outdoor Play", "Puzzles", "Art & Craft"]
  },
  {
    name: "Sports",
    subcategories: ["Cricket", "Football", "Badminton", "Running Shoes", "Gym Equipment", "Cycling", "Swimming", "Yoga"]
  },
  {
    name: "Grocery",
    subcategories: ["Fruits & Vegetables", "Dairy & Eggs", "Snacks", "Beverages", "Cooking Essentials", "Breakfast", "Organic", "Baby Food"]
  },
  {
    name: "Mobiles",
    subcategories: ["Smartphones", "Feature Phones", "Tablets", "Mobile Accessories", "Screen Guards", "Cases & Covers", "Power Banks", "Chargers"]
  }
];

export const homepageCategories = [
  { name: "Mobiles", icon: "smartphone", color: "#2874f0", link: "/products?category=Electronics" },
  { name: "Fashion", icon: "shirt", color: "#ff6161", link: "/products?category=Fashion" },
  { name: "Electronics", icon: "monitor", color: "#2874f0", link: "/products?category=Electronics" },
  { name: "Home & Kitchen", icon: "home", color: "#ffc200", link: "/products?category=Home & Kitchen" },
  { name: "Appliances", icon: "zap", color: "#00b9f5", link: "/products?category=Appliances" },
  { name: "Beauty", icon: "sparkles", color: "#ff6161", link: "/products?category=Beauty" },
  { name: "Sports", icon: "dumbbell", color: "#2874f0", link: "/products?category=Sports" },
  { name: "Toys", icon: "gamepad2", color: "#00b9f5", link: "/products?category=Toys" },
  { name: "Grocery", icon: "shopping-basket", color: "#388e3c", link: "/products?category=Grocery" },
  { name: "Travel", icon: "plane", color: "#2874f0", link: "/products" }
];

export const banners = [
  {
    id: 1,
    title: "Big Billion Days",
    subtitle: "India's Biggest Sale",
    discount: "Up to 80% Off",
    cta: "Shop Now",
    bgGradient: "linear-gradient(135deg, #2874f0 0%, #1565c0 100%)",
    textColor: "#FFE500",
    image: "https://images.unsplash.com/photo-1747586624185-14aa61f5f571?w=800&q=80",
    category: "Electronics"
  },
  {
    id: 2,
    title: "Fashion Festival",
    subtitle: "Top Brands at Lowest Prices",
    discount: "Min 50-80% Off",
    cta: "Explore Fashion",
    bgGradient: "linear-gradient(135deg, #c62828 0%, #880e4f 100%)",
    textColor: "#FFE500",
    image: "https://images.unsplash.com/photo-1583316174775-bd6dc0e9f298?w=800&q=80",
    category: "Fashion"
  },
  {
    id: 3,
    title: "Electronics Carnival",
    subtitle: "Latest Gadgets & Gizmos",
    discount: "Up to 40% Off",
    cta: "Shop Electronics",
    bgGradient: "linear-gradient(135deg, #1a237e 0%, #283593 100%)",
    textColor: "#FFE500",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80",
    category: "Electronics"
  },
  {
    id: 4,
    title: "Home Makeover",
    subtitle: "Transform Your Living Space",
    discount: "Up to 60% Off",
    cta: "Shop Home",
    bgGradient: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    textColor: "#FFE500",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    category: "Home & Kitchen"
  },
  {
    id: 5,
    title: "Mobile Mania",
    subtitle: "Best Smartphones of 2024",
    discount: "Up to 35% Off",
    cta: "Explore Mobiles",
    bgGradient: "linear-gradient(135deg, #4a148c 0%, #6a1b9a 100%)",
    textColor: "#FFE500",
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=80",
    category: "Electronics"
  }
];

export const dealOfTheDayProducts = products.filter(p => p.discount >= 40).slice(0, 6);
export const topOffersProducts = products.filter(p => p.isFeatured);
export const electronicsProducts = products.filter(p => p.category === "Electronics");
export const fashionProducts = products.filter(p => p.category === "Fashion");
export const beautyProducts = products.filter(p => p.category === "Beauty");
export const sportsProducts = products.filter(p => p.category === "Sports");
export const homeProducts = products.filter(p => p.category === "Home & Kitchen");
